name: cargo-audit

on:
  schedule:
    - cron: '17 0 * * *'
  push:
    paths: 
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - .github/workflows/cargo-audit.yml

jobs:
  cargo-audit:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
