name: Mutants on AWS Runners
on:
  push:
    branches:
      - codebuild
jobs:
  mutants-on-aws-runners:
    runs-on:
      - codebuild-mutants-runners-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: beta
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        name: Install nextest using install-action
        with:
          tool: nextest
      - run: cargo run --release mutants -j4 -vV
      - uses: actions/upload-artifact@v4
        with:
          name: mutants.out
          path: mutants.out
