name: Illumos Integration Tests

on:
  push:
    branches: [ "main", "illumos-ci" ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-illumos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Tests inside OmniOS VM
        uses: vmactions/omnios-vm@v1
        with:
          cache-after-prepare: true
          prepare: |
            pkg refresh
            pkg install developer/build/onbld rust
          run: |
            whoami
            env
            cat /etc/release || true
            cargo test
